theme: jekyll-theme-minimal
title: CYBERBEAT Music Player
description: A modern music player with waveform visualization
url: "https://lavendergongs.github.io"

# 构建设置
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# 默认布局
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# 排除文件
exclude:
  - node_modules
  - backend2
  - .git
  - .vscode
  - package.json
  - package-lock.json
  - vercel.json
  - vercel-build.sh
  - .github
  - src
  - docs/assets

# 包含文件
include:
  - assets
  - index.html
  - favicon.ico

# 构建设置
sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules 