name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者 master，取决于您的默认分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          # 复制必要的文件到 docs 目录
          cp -r index.html style.css mobile.css config.js my.js musicPlayer.js likedList.js playlist.js share.js theme.js docs/
          cp -r public docs/
          cp -r uploads docs/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages 